##### Select All
GET http://localhost:3000/capstones.json

##### Select One
GET http://localhost:3000/capstones/4.json

##### Create
POST http://localhost:3000/capstones.json
Content-Type: application/json

{
  "student_id": "1",
  "name": "Some named capstone",
  "description": "This some descirption about some named capstone",
  "url": "www.google.com",
  "screenshot": ""

}

##### Update
PATCH http://localhost:3000/capstones/2.json
Content-Type: application/json

{
  "student_id": "4",
  "name": "Star wars",
  "description": "In a galaxy far far away",
  "url": "www.starwars.com",
  "screenshot": ""
}

##### Delete
DELETE http://localhost:3000/capstones/3.json
