### Students Index
GET http://localhost:3000/students.json

### Students Show
GET http://localhost:3000/students/1.json

### Student Create
POST http://localhost:3000/students
Content-Type: application/json

{
	"first_name": "Test",
	"email": "email@example.com",
	"password": "password",
	"password_confirmation": "password"
}

### Students Update
PATCH http://localhost:3000/students/1
Content-Type: application/json

{
	"website_url": "http://www.example.com/"
}

### Students Destroy
DELETE http://localhost:3000/students/1
Content-Type: application/json