##### Select All
GET http://localhost:3000/skills.json

##### Select One
GET http://localhost:3000/skills/2.json

##### Create
POST http://localhost:3000/skills.json
Content-Type: application/json

{
  "student_id": 1,
  "skill": "Some new skill"
}

##### Update
PATCH http://localhost:3000/skills/2.json
Content-Type: application/json

{
  "student_id": 1,
  "skill": "Another new skill"
}

##### Delete
DELETE http://localhost:3000/skills/3.json
